import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF4F53B6),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFE1E0FF),
  onPrimaryContainer: Color(0xFF03006D),
  secondary: Color(0xFF005AC1),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD8E2FF),
  onSecondaryContainer: Color(0xFF001A41),
  tertiary: Color(0xFF1A60A5),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFD4E3FF),
  onTertiaryContainer: Color(0xFF001C39),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1B1B1F),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1B1B1F),
  surfaceVariant: Color(0xFFE4E1EC),
  onSurfaceVariant: Color(0xFF46464F),
  outline: Color(0xFF777680),
  onInverseSurface: Color(0xFFF3EFF4),
  inverseSurface: Color(0xFF313034),
  inversePrimary: Color(0xFFBFC1FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF4F53B6),
  outlineVariant: Color(0xFFC7C5D0),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFBFC1FF),
  onPrimary: Color(0xFF1D2086),
  primaryContainer: Color(0xFF363A9C),
  onPrimaryContainer: Color(0xFFE1E0FF),
  secondary: Color(0xFFADC6FF),
  onSecondary: Color(0xFF002E69),
  secondaryContainer: Color(0xFF004494),
  onSecondaryContainer: Color(0xFFD8E2FF),
  tertiary: Color(0xFFA4C9FF),
  onTertiary: Color(0xFF00315D),
  tertiaryContainer: Color(0xFF004883),
  onTertiaryContainer: Color(0xFFD4E3FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1B1B1F),
  onBackground: Color(0xFFE5E1E6),
  surface: Color(0xFF1B1B1F),
  onSurface: Color(0xFFE5E1E6),
  surfaceVariant: Color(0xFF46464F),
  onSurfaceVariant: Color(0xFFC7C5D0),
  outline: Color(0xFF918F9A),
  onInverseSurface: Color(0xFF1B1B1F),
  inverseSurface: Color(0xFFE5E1E6),
  inversePrimary: Color(0xFF4F53B6),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFBFC1FF),
  outlineVariant: Color(0xFF46464F),
  scrim: Color(0xFF000000),
);

const colorPickerColorList = [
  Colors.blue,
  Colors.redAccent,
  Colors.orange,
  Colors.purple,
  Colors.pinkAccent,
  Colors.amber,
  Colors.cyan,
  Colors.deepPurple,
  Colors.green,
  Colors.indigo,
  Colors.lime,
  Colors.teal,
  Colors.tealAccent,
  Colors.lightBlueAccent,
  Colors.blueGrey,
  Colors.grey,
];