// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzDY6GcmKRlepNUtwigQlbQd2x0WWt3Q',
    appId: '1:315562337277:web:aba3f97f7d70dfaa062f94',
    messagingSenderId: '315562337277',
    projectId: 'coredax-meeting',
    authDomain: 'coredax-meeting.firebaseapp.com',
    storageBucket: 'coredax-meeting.appspot.com',
    measurementId: 'G-CP87HSDFH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB--ZCLMyKqT2zdBR4zwf9R3ICQ3nLvtKU',
    appId: '1:315562337277:android:bc1d62e770a65159062f94',
    messagingSenderId: '315562337277',
    projectId: 'coredax-meeting',
    storageBucket: 'coredax-meeting.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ2uP4j5ZU2L_BdayxxQsZ3i5HJCQqrnQ',
    appId: '1:315562337277:ios:82bb4dc7077d487b062f94',
    messagingSenderId: '315562337277',
    projectId: 'coredax-meeting',
    storageBucket: 'coredax-meeting.appspot.com',
    iosBundleId: 'com.coredax.meetingRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ2uP4j5ZU2L_BdayxxQsZ3i5HJCQqrnQ',
    appId: '1:315562337277:ios:2d8311c0560f59c0062f94',
    messagingSenderId: '315562337277',
    projectId: 'coredax-meeting',
    storageBucket: 'coredax-meeting.appspot.com',
    iosBundleId: 'com.coredax.meetingRoom.RunnerTests',
  );
}
